# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04, macos-latest]
        compilers: [GCC, clang]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: "Clone w/ submodules"
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Setup OpenGL
        uses: openrndr/setup-opengl@v1
        
      # Configure via CMake
      - name: Configure
        shell: cmake -P {0}
        run: |
          set(ENV{CC} ${{ matrix.compiler }})
          set(ENV{CXX} ${{ matrix.compiler }})
          
