# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: ${{ matrix.config.name }}
    # The type of runner that the job will run on
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
        - { 
            name: "Ubuntu GCC",
            os:   "ubuntu-latest",
            cc:   "gcc",
            cxx:  "g++"
          }
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: "Clone w/ submodules"
        uses: actions/checkout@v2
        with:
          submodules: true
          recursive:  true
      - name: Setup OpenGL
        uses: openrndr/setup-opengl@v1
      - name: Install misssing packages
        run: sudo apt install libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev
        
      # Configure via CMake
      - name: Configure
        run: cmake -S . -B build -DCMAKE_CXX_COMPILER=${{ matrix.config.cxx }}
              # Configure via CMake
      - name: Build
        run: cmake -S . -B build --build
